apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: websocket-chat-api
  description: WebSocket 기반 실시간 채팅 API
  tags:
    - websocket
    - chat
    - real-time
    - messaging
  links:
    - url: https://github.com/your-org/RND-NX/tree/main/libs/be/websocket/src/chat
      title: API Implementation
      icon: github
    - url: https://github.com/your-org/RND-NX/blob/main/libs/be/websocket/src/chat/chat-test.html
      title: Test Client
      icon: web
spec:
  type: websocket
  lifecycle: production
  owner: backend-team
  system: rnd-nx-framework
  definition: |
    # WebSocket Chat API
    
    ## Connection
    ```
    ws://localhost:3000/chat
    ```
    
    ## Events
    
    ### Client -> Server
    - `chat:message` - 메시지 전송
      ```json
      {
        "roomId": "string",
        "message": "string",
        "userId": "string"
      }
      ```
    
    - `chat:join` - 채팅방 참여
      ```json
      {
        "roomId": "string",
        "userId": "string"
      }
      ```
    
    - `chat:leave` - 채팅방 나가기
      ```json
      {
        "roomId": "string",
        "userId": "string"
      }
      ```
    
    ### Server -> Client
    - `chat:message` - 메시지 수신
    - `chat:user-joined` - 사용자 입장 알림
    - `chat:user-left` - 사용자 퇴장 알림

