---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# Google OAuth User
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jidaisy
  annotations:
    # This annotation is required for emailMatchingUserEntityAnnotation resolver
    backstage.io/managed-by-location: 'url:file:///examples/org.yaml'
spec:
  profile:
    displayName: Ji Won
    email: jidaisy@vntgcorp.com
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
