---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# Google OAuth User
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jidaisy
  annotations:
    # This annotation is required for emailMatchingUserEntityAnnotation resolver
    backstage.io/managed-by-location: 'url:file:///examples/org.yaml'
spec:
  profile:
    displayName: Ji Won Seo
    email: jidaisy@vntgcorp.com
    picture: https://avatars.githubusercontent.com/u/xxxxx
  memberOf: [platform-team, backend-team, admins, frontend-team]
---
# GitHub OAuth User - Add your GitHub username here
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: jidaisy82  # GitHub username (must match your actual GitHub username)
  annotations:
    backstage.io/managed-by-location: 'url:file:///examples/org.yaml'
spec:
  profile:
    displayName: Ji Won Seo
    # email: jidaisy@vntgcorp.com  # Your email associated with GitHub
  memberOf: [platform-team, backend-team, admins, frontend-team]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  profile:
    displayName: Guests Group
    description: 읽기 전용 접근 권한
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: developers
spec:
  type: team
  profile:
    displayName: Developer Group
    description: 개발 관련 리소스 접근 권한
  children: []
  parent: admins
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: admins
spec:
  type: team
  profile:
    displayName: Admin Group
    description: 시스템 전체 관리 권한
  children: []
---
# Platform Team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: 플랫폼 엔지니어링 팀
spec:
  type: team
  profile:
    displayName: Platform Engineering Team
    email: platform@vntgcorp.com
    picture: https://example.com/team-logo.png
  children:
    - backend-team
    - frontend-team
    - design-team
    - devops-team

---
# Backend Team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: backend-team
spec:
  type: team
  profile:
    displayName: Backend Team
    email: backend@vntgcorp.com
  parent: platform-team
  children: []

---
# Frontend Team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: frontend-team
spec:
  type: team
  profile:
    displayName: Frontend Team
    email: frontend@vntgcorp.com
  parent: platform-team
  children: []

---
# Design Team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: design-team
spec:
  type: team
  profile:
    displayName: Design System Team
    email: design@vntgcorp.com
  parent: platform-team
  children: []

---
# DevOps Team
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: devops-team
spec:
  type: team
  profile:
    displayName: DevOps Team
    email: devops@vntgcorp.com
  parent: platform-team
  children: []
---

