apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: argocd-prod-shared
  description: ArgoCD Application - Production 환경 공유 리소스 배포
  tags:
    - argocd
    - kubernetes
    - gitops
    - prod
  annotations:
    argocd/app-name: prod-shared
  links:
    - url: https://argocd.your-domain.com/applications/prod-shared
      title: ArgoCD Dashboard
      icon: dashboard
    - url: https://github.com/your-org/RND-NX/tree/main/k8s/argocd/apps/shared/prod.yaml
      title: Application Definition
      icon: github
spec:
  type: argocd-application
  lifecycle: production
  owner: devops-team
  system: rnd-nx-framework
  dependsOn:
    - resource:default/gke-prod-cluster

