apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: loki-grafana-stack
  description: Loki + Grafana 로깅 및 모니터링 스택
  tags:
    - logging
    - monitoring
    - grafana
    - loki
    - observability
  links:
    - url: http://localhost:3000
      title: Grafana Dashboard
      icon: dashboard
    - url: https://github.com/your-org/RND-NX/tree/main/libs/be/log-pipeline/loki-grafana
      title: Stack Configuration
      icon: github
spec:
  type: monitoring-system
  lifecycle: production
  owner: devops-team
  system: rnd-nx-framework

